//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Photon.Pun.Demo.Cockpit.Forms.CreateRoomUiForm.OnSubmitEvent))]
	public class PropertyProvider_Photon_Pun_Demo_Cockpit_Forms_CreateRoomUiForm_OnSubmitEvent : Unity.VisualScripting.SerializedPropertyProvider<Photon.Pun.Demo.Cockpit.Forms.CreateRoomUiForm.OnSubmitEvent>
	{
	}
}
